import { join } from "node:path";
import { atomicWriteSync } from "../atomic-write.js";
import { updateAssessmentProjectionPath } from "./store.js";
import type { AssessmentRun } from "./types.js";

function projectionPath(basePath: string, run: AssessmentRun): string {
  return run.scope.milestoneId
    ? join(basePath, ".gsd", "milestones", run.scope.milestoneId, "assessments", `${run.runId}.md`)
    : join(basePath, ".gsd", "assessments", `${run.runId}.md`);
}

export function renderAssessmentRunProjection(run: AssessmentRun): string {
  const lines = [
    "---",
    `run_id: ${JSON.stringify(run.runId)}`,
    `gate_id: ${JSON.stringify(run.gateId)}`,
    `lifecycle: ${JSON.stringify(run.lifecycle)}`,
    `effect: report-only`,
    `status: ${JSON.stringify(run.status)}`,
    ...(run.verdict ? [`verdict: ${JSON.stringify(run.verdict)}`] : []),
    ...(run.testedSourceRevision ? [`tested_source_revision: ${JSON.stringify(run.testedSourceRevision)}`] : []),
    ...(run.inputDigest ? [`input_digest: ${JSON.stringify(run.inputDigest)}`] : []),
    ...(run.repositoryRevision ? [`repository_revision: ${JSON.stringify(run.repositoryRevision)}`] : []),
    `started_at: ${JSON.stringify(run.startedAt)}`,
    ...(run.completedAt ? [`completed_at: ${JSON.stringify(run.completedAt)}`] : []),
    "---",
    "",
    `# Assessment ${run.runId}`,
    "",
    `- Gate: \`${run.gateId}\``,
    `- Status: \`${run.status}\``,
    `- Lifecycle: \`${run.lifecycle}\``,
    `- Invocation: ${run.invocationReason || "not recorded"}`,
    `- Approval: ${run.approval ? `${run.approval.method} at ${run.approval.approvedAt}` : "not recorded"}`,
    `- Capabilities: ${run.toolProfile.length ? run.toolProfile.map((item) => `\`${item}\``).join(", ") : "none"}`,
    `- Blocked capabilities: ${run.blockedCapabilities.length ? run.blockedCapabilities.map((item) => `\`${item}\``).join(", ") : "none"}`,
    `- Source binding: ${run.testedSourceRevision ? `\`${run.testedSourceRevision}\`` : run.inputDigest ? `input \`${run.inputDigest}\`` : "none"}`,
    ...(run.repositoryRevision ? [`- Repository revision: \`${run.repositoryRevision}\``] : []),
    `- Target: ${run.targetUrl ?? "none"}`,
    `- Model/provider: ${run.model ?? "default"} / ${run.provider ?? "default"}`,
    "",
    "## Summary",
    "",
    run.summary || "No summary was recorded.",
    "",
    "## Findings",
    "",
  ];
  if (run.findings.length === 0) lines.push("No findings.", "");
  for (const finding of run.findings) {
    lines.push(
      `### ${finding.id}: ${finding.title}`,
      "",
      `- Severity: \`${finding.severity}\``,
      `- Category: \`${finding.category}\``,
      ...(finding.affectedPaths.length ? [`- Affected: ${finding.affectedPaths.map((path) => `\`${path}\``).join(", ")}`] : []),
      "",
      finding.description,
      "",
      ...finding.evidence.map((evidence) => `- Evidence (${evidence.kind}): \`${evidence.ref}\`${evidence.note ? ` — ${evidence.note}` : ""}`),
      ...(finding.recommendedAction ? ["", `Recommended action: ${finding.recommendedAction}`] : []),
      "",
    );
  }
  if (run.failureReason) lines.push("## Failure", "", run.failureReason, "");
  if (run.policyViolations.length) {
    lines.push("## Policy violations", "", ...run.policyViolations.map((item) => `- ${item}`), "");
  }
  lines.push(
    "> This file is a readable projection. The canonical record is stored in GSD SQLite; do not edit this file directly.",
    "",
  );
  return lines.join("\n");
}

export function writeAssessmentRunProjection(basePath: string, run: AssessmentRun): string {
  const path = projectionPath(basePath, run);
  atomicWriteSync(path, renderAssessmentRunProjection(run), "utf8");
  updateAssessmentProjectionPath(run.runId, path);
  return path;
}
